#ifndef INCLUDE_CONSTANTS_H_
#define INCLUDE_CONSTANTS_H_

#define SERVER_CONTROL_PORT 21
#define SERVER_DATA_PORT 20
#define SERVER_ADDR "127.0.0.1"

#define SOCKET_ERR -1
#define OK 0

#endif /* INCLUDE_CONSTANTS_H_ */
